# Profile Template for Clash Verge

#---------------------------------------------------#
## 更新时间：2024-12-25 10:47:56
## 链接地址：
#---------------------------------------------------#

# Mixed-port 代理端口
mixed-port: 7890 

# Linux 和 macOS 的 redir 代理端口
redir-port: 7892 

# 允许局域网的连接
allow-lan: false


# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: silent
# Clash 的 RESTful API
external-controller: '0.0.0.0:9090'

# RESTful API 的口令
secret: '' 

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: folder

dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:5450
  enhanced-mode: fake-ip
  fake-ip-range: 198.19.0.1/16
  default-nameserver:
    - 223.5.5.5
    - 223.6.6.6
    - 1.0.0.1
    - 208.67.222.222
    - 1.2.4.8
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://1.1.1.1/dns-query
    - tls://dns.adguard.com:853
  fallback:
    - tls://223.5.5.5:853
    - https://223.5.5.5/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4

  
proxies:
    - {"name":"🇺🇲 自建｜美国-CF-Vless","type":"vless","server":"","port":443,"uuid":"","tls": true,"sni":"","network":"ws","ws-opts":{"headers":{"Host": ""}, "path": ""},"alpn":[]}

proxy-groups:
-
  name: '🚀 节点选择'
  type: select
  proxies:
    - '🔑 手动选择'
    - DIRECT
-
  name: '🔑 手动选择'
  type: select
  proxies:
    - '🇺🇲 自建｜美国-CF-Vless'
    - '🇯🇵 自建｜日本-CF-Vless'
    - DIRECT
-
  name: '☎️ 电报消息'
  type: select
  proxies:
    - '🚀 节点选择'
    - '🔑 手动选择'
    - 🇺🇸美国节点
    - 🇯🇵日本节点
    - DIRECT
-
  name: '📺 BiliBili'
  type: select
  proxies:
    - DIRECT
    - '🚀 节点选择'
    - '🔑 手动选择'
-
  name: '🎬 YouTube'
  type: select
  proxies:
    - '🚀 节点选择'
    - '🔑 手动选择'
    - 🇺🇸美国节点
    - 🇯🇵日本节点
    - DIRECT
-
  name: '📷 TikTok'
  type: select
  proxies:
    - '🚀 节点选择'
    - '🔑 手动选择'
    - 🇺🇸美国节点
    - 🇯🇵日本节点
    - DIRECT
-
  name: '🎥 Netflix'
  type: select
  proxies:
    - '🚀 节点选择'
    - '🔑 手动选择'
    - 🇺🇸美国节点
    - 🇯🇵日本节点
    - DIRECT
-
  name: '📹 Disney+'
  type: select
  proxies:
    - '🚀 节点选择'
    - '🔑 手动选择'
    - 🇺🇸美国节点
    - 🇯🇵日本节点
    - DIRECT
-
  name: '🎼 Emby'
  type: select
  proxies:
    - '🚀 节点选择'
    - '🔑 手动选择'
    - 🇺🇸美国节点
    - 🇯🇵日本节点
    - DIRECT
-
  name: '🛡️ 隐私防护'
  type: select
  proxies:
    - REJECT
    - DIRECT
    - '🚀 节点选择'
-
  name: '🎮 游戏平台'
  type: select
  proxies:
    - DIRECT
    - '🚀 节点选择'
    - '🔑 手动选择'
-
  name: '⏬ 下载平台'
  type: select
  proxies:
    - DIRECT
    - '🚀 节点选择'
    - '🔑 手动选择'
-
  name: '🌲 BT种子'
  type: select
  proxies:
    - DIRECT
    - '🚀 节点选择'
    - '🔑 手动选择'
-
  name: '🇨🇳 国内流量'
  type: select
  proxies:
    - DIRECT
    - '🚀 节点选择'
    - '🔑 手动选择'
-
  name: '🚫 广告拦截'
  type: select
  proxies:
    - REJECT
    - DIRECT
-
  name: '🚩 社交平台IP归属地'
  type: select
  proxies:
    - DIRECT
    - '🚀 节点选择'
    - '🔑 手动选择'
-
  name: '🐟 漏网之鱼'
  type: select
  proxies:
    - '🚀 节点选择'
    - '🔑 手动选择'
    - DIRECT
-
  name: '🛠️ 故障转移'
  type: fallback
  proxies:
    - '🔑 手动选择'
  url: 'http://www.gstatic.com/generate_204'
  interval: 500
-
  name: 🇺🇸美国节点
  type: select
  proxies:
    - '🇺🇲 自建｜美国-CF-Vless'
    - DIRECT
-
  name: 🇯🇵日本节点
  type: select
  proxies:
    - '🇯🇵 自建｜日本-CF-Vless'
    - DIRECT

# 规则
rule-providers:
  IPfake:
    type: http
    behavior: classical
    url: "http://129.226.210.119/rule-provider.yaml"
    path: ./Rules/IPfake.yaml
    interval: 259200    
  BiliBili:
    type: http
    behavior: classical
    url: "http://129.226.210.119/BiliBili.yaml"
    path: ./Rules/bilibili.yaml
    interval: 259200
  Disney:
    type: http
    behavior: classical
    url: "http://129.226.210.119/Disney.yaml"
    path: ./Rules/Disney.yaml
    interval: 259200

  Netflix:
    type: http
    behavior: classical
    url: "http://129.226.210.119/Netflix.yaml"
    path: ./Rules/Netflix.yaml
    interval: 259200

  TikTok:
    type: http
    behavior: classical
    url: "http://129.226.210.119/TikTok.yaml"
    path: ./Rules/TikTok.yaml
    interval: 259200

  YouTube:
    type: http
    behavior: classical
    url: "http://129.226.210.119/YouTube.yaml"
    path: ./Rules/YouTube.yaml
    interval: 259200

  Telegram:
    type: http
    behavior: classical
    url: "http://129.226.210.119/Telegram.yaml"
    path: ./Rules/Telegram.yaml
    interval: 259200

  Emby:
    type: http
    behavior: classical
    url: "http://129.226.210.119/Emby.yaml"
    path: ./Rules/Emby.yaml
    interval: 259200

  Game:
    type: http
    behavior: classical
    url: "http://129.226.210.119/Game.yaml"
    path: ./Rules/Game.yaml
    interval: 259200

  BanEasyPrivacy:
    type: http
    behavior: classical
    url: "http://129.226.210.119/Privacy_Classical.yaml"
    path: ./Rules/BanEasyPrivacy.yaml
    interval: 259200

  Advertising:
    type: http
    behavior: classical
    url: "http://129.226.210.119/AdvertisingLite_Classical.yaml"
    path: ./Rules/Advertising.yaml
    interval: 259200

  Download:
    type: http
    behavior: classical
    url: "http://129.226.210.119/Download.yaml"
    path: ./Rules/Download.yaml
    interval: 259200

  PrivateTracker:
    type: http
    behavior: domain
    url: "http://129.226.210.119/PrivateTracker.yaml"
    path: ./Rules/PrivateTracker.yaml
    interval: 259200

  Global:
    type: http
    behavior: classical
    url: "http://129.226.210.119/Global_Classical.yaml"
    path: ./Rules/Global.yaml
    interval: 259200

  Lan:
    type: http
    behavior: classical
    url: "http://129.226.210.119/Lan.yaml"
    path: ./Rules/Lan.yaml
    interval: 259200
    
rules:
  - DOMAIN-SUFFIX,gjfzpt.cn,REJECT
  - DOMAIN-KEYWORD,gmail,🚀 节点选择
  - DOMAIN-KEYWORD,google,🚀 节点选择
  - DOMAIN-SUFFIX,1e100.net,🚀 节点选择
  - DOMAIN-SUFFIX,2mdn.net,🚀 节点选择
  - DOMAIN-SUFFIX,app-measurement.net,🚀 节点选择
  - DOMAIN-SUFFIX,g.co,🚀 节点选择
  - DOMAIN-SUFFIX,ggpht.com,🚀 节点选择
  - DOMAIN-SUFFIX,goo.gl,🚀 节点选择
  - DOMAIN-SUFFIX,googleapis.cn,🚀 节点选择
  - DOMAIN-SUFFIX,googleapis.com,🚀 节点选择
  - DOMAIN-SUFFIX,gstatic.cn,🚀 节点选择
  - DOMAIN-SUFFIX,gstatic.com,🚀 节点选择
  - DOMAIN-SUFFIX,gvt0.com,🚀 节点选择
  - DOMAIN-SUFFIX,gvt1.com,🚀 节点选择
  - DOMAIN-SUFFIX,gvt2.com,🚀 节点选择
  - DOMAIN-SUFFIX,gvt3.com,🚀 节点选择
  - DOMAIN-SUFFIX,xn--ngstr-lra8j.com,🚀 节点选择
  - DOMAIN-SUFFIX,youtu.be,🚀 节点选择
  - DOMAIN-SUFFIX,youtube-nocookie.com,🚀 节点选择
  - DOMAIN-SUFFIX,youtube.com,🚀 节点选择
  - DOMAIN-SUFFIX,yt.be,🚀 节点选择
  - DOMAIN-SUFFIX,ytimg.com,🚀 节点选择
  - SRC-IP-CIDR,219.143.187.136/32,REJECT
  - RULE-SET,BiliBili,📺 BiliBili
  - RULE-SET,YouTube,🎬 YouTube
  - RULE-SET,Netflix,🎥 Netflix
  - RULE-SET,Disney,📹 Disney+
  - RULE-SET,TikTok,📷 TikTok
  - RULE-SET,Emby,🎼 Emby
  - RULE-SET,Telegram,☎️ 电报消息
  - RULE-SET,Game,🎮 游戏平台
  - RULE-SET,BanEasyPrivacy,🛡️ 隐私防护
  - RULE-SET,Advertising,🚫 广告拦截
  - RULE-SET,Download,⏬ 下载平台
  - RULE-SET,PrivateTracker,🌲 BT种子
  - RULE-SET,IPfake,🚩 社交平台IP归属地
  - RULE-SET,Lan,🇨🇳 国内流量
  - RULE-SET,Global,🚀 节点选择
  - GEOIP,CN,🇨🇳 国内流量  
  - MATCH,🐟 漏网之鱼
